---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  install:
    crds: Create
  interval: 1h0m0s
  releaseName: ingress-controller
  targetNamespace: ingress-controller
  upgrade:
    crds: CreateReplace
