---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valut-3
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: valut-3
  targetNamespace: valut-3
  values:
    ui:
      activeVaultPodOnly: false
      annotations: {}
      enabled: true
      externalPort: 8200
      publishNotReadyAddresses: true
      serviceNodePort: null
      serviceType: LoadBalancer
