---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jenkins
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: jenkins
  targetNamespace: jenkins
  values:
    controller:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
        enabled: true
        hostName: jenkins.foxnheart.com
        tls:
        - hosts:
          - jenkins.foxnheart.com
          secretName: jenkins-ingress
      installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - configuration-as-code
      - ldap
      - kubernetes-client-api
      - kubernetes-cli
      - job-dsl
      - matrix-auth
      - pipeline-stage-view
      - folder-properties
      - github-oauth
    persistence:
      enabled: false
